# 1. ndarray与列表效率对比

In [1]:
# 导入随机数模块，导入时间模块，导入numpy模块同时加以别名'np'

In [2]:
import random
import time
import numpy as np

In [3]:
a = []
for i in range(100000000):
    a.append(random.random())
t1 = time.time()
sum1 = sum(a)
t2 = time.time()
b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2-t1,t5-t4)

0.3433823585510254 0.0640261173248291


# 2.创建nadarray
## 2.1 一维数组创建

In [4]:
import numpy as np
list1 = [1,2,3,4]
arr1 = np.array(list1)
print(type(arr1))
print(arr1)
print(list1,type(list1))

<class 'numpy.ndarray'>
[1 2 3 4]
[1, 2, 3, 4] <class 'list'>


In [5]:
arr2 = np.array(range(10))
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr3 = np.arange(0,10,2)
arr3

array([0, 2, 4, 6, 8])

## 2.2 创建二维数组

In [7]:
import numpy as np
list2 = [[1,2],[3,4],[5,6]]
arr = np.array(list2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

## 2.3 将数组转换成列表

### 将ndarray转化成list
数组.tolist()

In [8]:
a = np.array(["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"])
a
b = a.tolist()
b

['衬衫', '羊毛衫', '雪纺衫', '裤子', '高跟鞋', '袜子']

## 2.4 常用属性

In [9]:
list2 = [[3,4],[5,6],[7,8]]
arr1 = np.array(list2)
arr1

array([[3, 4],
       [5, 6],
       [7, 8]])

In [10]:
# 属性一般后面不加()，方法后面加()

In [11]:
arr1.ndim

2

In [12]:
arr1.shape

(3, 2)

In [13]:
arr1.size

6

## 2.5 修改形状

In [14]:
four = np.array([[1,2,3],[4,5,6]])
four.shape

(2, 3)

In [15]:
four.shape = (3,2)

In [16]:
four

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
five = four.reshape(2,3)
five

array([[1, 2, 3],
       [4, 5, 6]])

## 2.6 多维与一维相互转换

In [18]:
one = np.array(range(18))
one

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [19]:
two = one.reshape(3,6)
two

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [20]:
three = np.array(range(12)).reshape(3,4)
three

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
four = three.reshape(12,order = 'F')# F表示以列的顺序展开
four

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [22]:
four = three.reshape(12)# 默认情况下为C,以行的形式展开
four

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 2.7 维度拓展

In [23]:
# 三维数组的创建改变形状时数据数量改为三个数的积

In [24]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## 2.8数据类型

In [25]:
f = np.array([1,2,3,4,5], dtype = np.int16)
# 返回数组中每个元素的字节单位长度
print(f.itemsize)
# 获取数据类型
print(f.dtype)

2
int16


In [26]:
# 调整数据类型
f1 = f.astype(np.int64)
print(f1.itemsize)
print(f1.dtype)

8
int64


In [27]:
# 使用python语法，保留两位
print(round(random.random(),2))

0.87


In [28]:
# 拓展随机生成小数

arr = np.array([random.random() for i in range(10)])
# 取小数点后两位
print(np.round(arr,2))

[0.4  0.12 0.53 0.98 0.58 0.66 0.83 0.04 0.22 0.34]


## 2.9列表推导式

In [29]:
names = ['Bob','Tom','alice','Jerry','Wendy','Smith']
for name in names:
    print(name.upper())


BOB
TOM
ALICE
JERRY
WENDY
SMITH


In [30]:
names = ['Bob','Tom','alice','Jerry','Wendy','Smith']
new_names = [name.upper()for name in names]
print(new_names)

['BOB', 'TOM', 'ALICE', 'JERRY', 'WENDY', 'SMITH']


In [31]:
names = ['Bob','Tom','alice','Jerry','Wendy','Smith']
new_names = [name.upper()for name in names if len(name)>3]
print(new_names)


['ALICE', 'JERRY', 'WENDY', 'SMITH']


# 3数组的索引和切片

In [32]:
import numpy as np

In [33]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[3]

3

In [35]:
a[3:8:2]

array([3, 5, 7])

In [36]:
# 切片：
# start:stop:step

## 3.1多维数组切片

In [37]:
import numpy as np
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
a[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [39]:
a[1,3:5]

array([ 9, 10])

In [40]:
a[1:3,3:5]

array([[ 9, 10],
       [15, 16]])

In [41]:
# 数组的多行不连续切片需要双[[]]

In [42]:
a[[0,2,3]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

# 4数组数值修改

In [43]:
arr1 = np.arange(24).reshape(4,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [44]:
arr1[[0,1,3],] = 0

In [45]:
arr1

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [12, 13, 14, 15, 16, 17],
       [ 0,  0,  0,  0,  0,  0]])

In [46]:
# 列前边一定要加':,'

In [47]:
arr1[:,[1,3,4]] = 8

In [48]:
arr1

array([[ 0,  8,  0,  8,  8,  0],
       [ 0,  8,  0,  8,  8,  0],
       [12,  8, 14,  8,  8, 17],
       [ 0,  8,  0,  8,  8,  0]])

## 4.1 逻辑判断
1.&与
2.|或
3.~非

In [49]:
# & \ ~ 每一个关系式之间需要()隔开

In [50]:
arr2 = np.arange(24).reshape(4,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [51]:
arr2[(arr2>4) & (arr2<10)] = 0

In [52]:
arr2

array([[ 0,  1,  2,  3,  4,  0],
       [ 0,  0,  0,  0, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
arr2[(arr2<4) | (arr2>20) ] = 8

In [54]:
arr2

array([[ 8,  8,  8,  8,  4,  8],
       [ 8,  8,  8,  8, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20,  8,  8,  8]])

In [55]:
arr3 = np.arange(24).reshape(4,6)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [56]:
arr3[~(arr3>20)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## 4.2 三目运算
np.where(condition,x,y)满足条件x，不满足y

In [57]:
score = np.array([[30,50],[80,60],[90,77]])
result = np.where(score>=80,'良','一般')
result

array([['一般', '一般'],
       ['良', '一般'],
       ['良', '一般']], dtype='<U2')

# 5数组中的轴
二维数组中的轴

In [58]:
import numpy as np
arr1 = np.arange(24).reshape(4,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [59]:
np.sum(arr1)

276

In [60]:
np.sum(arr1,axis = 0)

array([36, 40, 44, 48, 52, 56])

In [61]:
np.sum(arr1,axis = 1)

array([ 15,  51,  87, 123])

In [62]:
import numpy as np
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
np.sum(a)

351

In [64]:
# 三维数据中'0'为Z轴

In [65]:
np.sum(a,axis = 0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [66]:
np.sum(a,axis = 1) # Y轴

array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])

In [67]:
np.sum(a,axis = 2) # X轴

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])

# 数组运算
## 6.1 数组与数之间的运算


In [68]:
import numpy as np 
t1 = np.arange(24).reshape((6,4))
print(t1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [69]:
print(t1 + 2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [70]:
print(t1*2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]


In [71]:
print(t1/2)

[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


## 6.2 数组与数组之间的运算

In [72]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [73]:
arr2 = np.arange(100,124).reshape(6,4)
arr2

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123]])

In [74]:
arr1 + arr2

array([[100, 102, 104, 106],
       [108, 110, 112, 114],
       [116, 118, 120, 122],
       [124, 126, 128, 130],
       [132, 134, 136, 138],
       [140, 142, 144, 146]])

In [75]:
arr1 * arr2

array([[   0,  101,  204,  309],
       [ 416,  525,  636,  749],
       [ 864,  981, 1100, 1221],
       [1344, 1469, 1596, 1725],
       [1856, 1989, 2124, 2261],
       [2400, 2541, 2684, 2829]])

## 6.3不同形状的多维数组运算
不同行不同列不能进行计算

In [76]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
arr2 = np.arange(18).reshape(3,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [78]:
# 行不同列不同不能进行计算

In [79]:
arr1 + arr2 

ValueError: operands could not be broadcast together with shapes (6,4) (3,6) 

## 6.4行数或者列数相同的一维数组和多维数组可以进行计算

In [80]:
arr1 = np.arange(24).reshape(4,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [81]:
arr2 = np.arange(6)

In [82]:
arr2

array([0, 1, 2, 3, 4, 5])

In [83]:
arr1 - arr2

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

纵向

In [84]:
arr1 = np.arange(24).reshape(4,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [85]:
arr2 = np.arange(4).reshape(4,1)

In [86]:
arr2


array([[0],
       [1],
       [2],
       [3]])

In [87]:
arr1 - arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

# 7数组计算

In [88]:
# 最大值

In [89]:
score = np.array([[40,50],[140,55],[94,150]])
print(score)
result = np.max(score)
result

[[ 40  50]
 [140  55]
 [ 94 150]]


150

In [90]:
score = np.array([[40,50],[140,55],[94,150]])
result = np.max(score,axis = 0)
result

array([140, 150])

In [91]:
score = np.array([[40,50],[140,55],[94,150]])
result = np.max(score,axis = 1)
result

array([ 50, 140, 150])

In [92]:
# 平均值

In [93]:
score = np.array([[40,50],[140,55],[94,150]])
result = np.mean(score)
result

88.16666666666667

In [94]:
score = np.array([[40,50],[140,55],[94,150]])
result = np.mean(score,0)
result

array([91.33333333, 85.        ])

In [95]:
score = np.array([[40,50],[140,55],[94,150]])
result = np.mean(score,1)
result

array([ 45. ,  97.5, 122. ])

In [96]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [97]:
print(arr)
print('*'*20)
# 计算数组的累加值
print(arr.cumsum(0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
********************
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


# 8数组的操作

In [98]:
l = [1,2,4,5]
l.append(8)
l

[1, 2, 4, 5, 8]

In [99]:
a = np.array(l)
a

array([1, 2, 4, 5, 8])

In [100]:
# 数组添加np.append(数组名,[添加值])

In [101]:
np.append(a,[3,4,5])

array([1, 2, 4, 5, 8, 3, 4, 5])

In [102]:
arr1 = np.arange(24).reshape(4,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [103]:
np.append(arr1,[3,4,5])# 没有指定轴都会按照一维数组来

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  3,  4,  5])

In [104]:
arr2 = np.arange(24).reshape(4,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [105]:
# 二维数的添加，添加内容需要使用[[]]

In [106]:
np.append(arr2,[[3,4,5,10,8,9]],0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 3,  4,  5, 10,  8,  9]])

In [107]:
arr3 = np.arange(24).reshape(4,6)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [108]:
np.append(arr3,[[7],[8],[9],[10]],1)

array([[ 0,  1,  2,  3,  4,  5,  7],
       [ 6,  7,  8,  9, 10, 11,  8],
       [12, 13, 14, 15, 16, 17,  9],
       [18, 19, 20, 21, 22, 23, 10]])

In [109]:
# insert添加方是 np.insert(需要添加的数组名,index,[需要添加的数据],axix=(轴)) insert方法内二维数组只需要一层[]

In [110]:
l1 = [1,2,3,4]
l1.insert(2,6)
l1

[1, 2, 6, 3, 4]

In [111]:
arr1 = np.arange(24).reshape(4,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
# insert添加只需一层[]

In [112]:
np.insert(arr1,1,[1,2,3,4,5,6])

array([ 0,  1,  2,  3,  4,  5,  6,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [113]:
arr2 = np.arange(24).reshape(4,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [114]:
np.insert(arr2,1,[1,2,3,4,5,6],axis = 0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [115]:
arr3 = np.arange(24).reshape(4,6)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [116]:
np.insert(arr3,1,[3,4,5,6],axis = 1)

array([[ 0,  3,  1,  2,  3,  4,  5],
       [ 6,  4,  7,  8,  9, 10, 11],
       [12,  5, 13, 14, 15, 16, 17],
       [18,  6, 19, 20, 21, 22, 23]])

In [117]:
arr4 = np.arange(24).reshape(4,6)
arr4

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [118]:
np.delete(arr4,4)

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [119]:
arr4 = np.arange(24).reshape(4,6)
arr4

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

删完之产生一个新的数组

In [120]:
# 使用delete删除 np.delete(需要删除的数组名,index,axis = (轴))

In [121]:
np.delete(arr4,2,axis = 0) 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

arr4中依然存在，说明产生了一个新的数组

In [122]:
arr4

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [123]:
np.delete(arr4,3,axis = 1)

array([[ 0,  1,  2,  4,  5],
       [ 6,  7,  8, 10, 11],
       [12, 13, 14, 16, 17],
       [18, 19, 20, 22, 23]])